#!/bin/sh

if [ -f /usr/lib/games/scottfree/"$1".dat ]; then
	/usr/lib/games/scottfree/runtime /usr/lib/games/scottfree/$1.dat
else
	echo "Unknown game. Choose from:"
	(cd /usr/lib/games/scottfree; ls *.dat) | sed -e "s/^/    /" | sed "s/.dat$//"
fi

