SSL_BASE=SYSTEM \
OPTIM="$RPM_OPT_FLAGS" \
	./configure --prefix=/usr \
	--sbindir=/usr/sbin/ \
	--libexecdir=/usr/lib/apache \
	--sysconfdir=/etc/httpd/conf \
	--serverroot=/etc/httpd \
	--datadir=/home/httpd \
	--includedir=/usr/include/apache \
	--logfiledir=/var/log/httpd \
	--localstatedir=/var \
	--runtimedir=/var/run \
	--proxycachedir=/var/cache/httpd \
	--with-perl=/usr/bin/perl \
	--enable-module=ssl \
	--enable-module=all \
	--enable-shared=max \
	--disable-rule=WANTHSREGEX \
	--disable-rule=SSL_COMPAT   \
	--add-module=/usr/src/rpm/SOURCES/mod_bandwidth.c
