#!/bin/sh
# quake-server
# qui mai  7 16:15:54 EST 1998
#
# chkconfig: 345 98 10
# description: quake server
# description(pt_BR): Ativa/Desativa servidor quake
# processname: unixded
#
# seg nov  9 19:14:26 EDT 1998 - <aurelio@conectiva.com.br>
# incrementado com reload, restart
# arrumado bug com o nome do processo

# Biblioteca de funções
. /etc/rc.d/init.d/functions

DIR_HOME=/usr/lib/quake
PROC_NAME=unixded
PID_FILE=/var/run/$PROC_NAME.pid

case "$1" in
  start)
	cd $DIR_HOME
	gprintf "Starting %s server: " "quake"
	# deixe as '' pois é executado um eval para expandir a variável
	daemon_cnc '/usr/sbin/$PROC_NAME > /dev/null &'
	;;
  stop)
	gprintf "Stopping %s server: " "quake"
	killproc $PROC_NAME
	rm -f /var/lock/subsys/$PROC_NAME
	gprintf "done\n"
	;;
  status)
  	gprintf "Status %s: " "quake"
	status $PROC_NAME
	;;
  restart|reload)
        $0 stop
        $0 start
        ;;
  *)
	gprintf "Usage: %s {start|stop|status|restart|reload}\n" "quake-server"
	exit 1
	;;
esac

exit 0
