#!/bin/sh
# quake2-server
# qui mai  7 16:15:54 EST 1998
#
# chkconfig: - 98 10
# description: quake2 server
# description(pt_BR): Ativa/Desativa servidor quake2
# processname: quake2id
#
# seg nov  9 19:14:26 EDT 1998 - <aurelio@conectiva.com.br>
# incrementado com reload, restart, inicializar, parar
# arrumado bug com o nome do processo

# Biblioteca de funções
. /etc/rc.d/init.d/functions

DIR_HOME=/usr/lib/quake2
PROC_NAME=quake2id
ARQ_PID=/var/run/$PROC_NAME.pid

case "$1" in
  start)
	gprintf "Starting %s server: " "quake2"
	cd $DIR_HOME
	# deixe as '' pois é executado um eval para expandir a variável
	daemon_cnc '/usr/bin/$PROC_NAME +set dedicated 1 +exec server.cfg > /dev/null &'
	;;
  stop)
	gprintf "Stopping %s server: " "quake2"
	killproc $PROC_NAME
	rm -f /var/lock/subsys/$PROC_NAME
	gprintf "done\n"
	;;
  status)
  	gprintf "Status %s server: " "quake2"
	status $PROC_NAME
	;;
  restart|reload)
        $0 stop
        $0 start
        ;;
  *)
	gprintf "Usage: %s {start|stop|status|restart|reload}\n" "quake2-server"
	exit 1
	;;
esac

exit 0
